remote_theme: pages-themes/minimal@v0.2.0
title: Rama
logo: /assets/img/Picsart_24-12-02_20-59-55-934.png
description: my site about my job and life 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal    
