remote_theme: pages-themes/minimal@v0.2.0
title:     Minimal theme
logo: /assets/img/logo2.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal    
